environment: production
chdir: /opt/apps/myapp/current/
address: 127.0.0.1
user: wang
group: wang
port: 8000
pid: /opt/apps/myapp/current/tmp/thin.pid
rackup: /opt/apps/myapp/current/config.ru
log: /opt/apps/myapp/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true